version: "3.6"

services:
  fe:
    image: node:14
    restart: "no"
    user: node
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    ports:
      - 5000:5000
      - 6006:6006 # Storybook
    command: ["yarn", "workspace", "@thomaspwilson/www", "run", "develop"]

  storybook:
    image: node:14
    restart: "no"
    working_dir: /usr/src
    user: node
    ports:
      - 6006:6006 # Storybook
    command: ["yarn", "workspace", "@thomaspwilson/ui", "run", "storybook"]
    volumes:
      - .:/usr/src
