version: "3.6"

services:
  fe:
    image: node:20
    restart: "no"
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    command: ["yarn", "start"]

  storybook:
    image: node:20
    restart: "no"
    ports:
      - 6006:6006
    command: ['yarn', 'storybook']
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
