version: "3.6"

services:
  web:
    image: node:14
    restart: "no"
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/srv/app
      - .docker/entrypoint:/entrypoint:ro
    working_dir: /srv/app
    environment:
      - NODE_ENV=development
    command: ["yarn", "webpack-dev-server"]
    entrypoint: /entrypoint
